In [1]:
import numpy as np
import matplotlib.pyplot as plt
import mltools.funcs as funcs
import mltools.pca as pca
import mltools.location_scatter as location
import mltools.plots as plots
import sklearn.datasets as datasets
import sklearn.preprocessing as preprocessing

In [2]:
X, Y = datasets.load_wine(return_X_y=True)
print(X.shape)

(178, 13)


In [3]:
print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [4]:
X = preprocessing.scale(X)

In [5]:
print(X)

[[ 1.519 -0.562  0.232 ...  0.362  1.848  1.013]
 [ 0.246 -0.499 -0.828 ...  0.406  1.113  0.965]
 [ 0.197  0.021  1.109 ...  0.318  0.789  1.395]
 ...
 [ 0.333  1.745 -0.389 ... -1.612 -1.485  0.281]
 [ 0.209  0.228  0.013 ... -1.568 -1.401  0.296]
 [ 1.395  1.583  1.365 ... -1.524 -1.429 -0.595]]


In [6]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
