# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
print(a.dtype, a.shape)

int64 (5,)


In [5]:
a.astype(np.double)

array([1., 2., 3., 4., 5.])

In [6]:
a.sum(), a.min(), a.max()

(15, 1, 5)

In [7]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
a.reshape(1,-1,)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
A = np.array([[1,2,3],[4,5,6]], np.double)
b = np.array([1.,2.,3.])

In [18]:
c = np.array([4.,5.,6.])

In [19]:
b.dot(c)

32.0

In [20]:
np.dot(b, c)

32.0

In [17]:
print(A)
A.dot(b)

[[1. 2. 3.]
 [4. 5. 6.]]


array([14., 32.])

In [18]:
np.dot(A,b)

array([14., 32.])

In [21]:
A @ b

array([14., 32.])

In [22]:
b @ c

32.0

In [23]:
A.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [24]:
A @ A.T

array([[14., 32.],
       [32., 77.]])

In [25]:
A.T @ A

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [26]:
B = A @ A.T
print(B)

[[14. 32.]
 [32. 77.]]


In [27]:
np.linalg.inv(B)

array([[ 1.42592593, -0.59259259],
       [-0.59259259,  0.25925926]])

In [28]:
np.linalg.det(B)

54.00000000000001

In [29]:
np.c_[b, c]

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [31]:
np.r_[b.reshape(1,-1), c.reshape(1,-1)]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
np.linspace(-1,1,11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [34]:
xx = np.linspace(-1,1,11)
yy = np.linspace(-1,1,21)

In [35]:
XX, YY = np.meshgrid(xx, yy)
print(XX)
print(YY)

[[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
 [-1.  -0.8 -0

In [36]:
b + c

array([5., 7., 9.])

In [37]:
b * c

array([ 4., 10., 18.])

In [38]:
b ** c

array([  1.,  32., 729.])

In [39]:
np.exp(b)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [40]:
np.sin(c)

array([-0.7568025 , -0.95892427, -0.2794155 ])