In [1]:
import numpy as np

In [4]:
A = np.array([[1,2],[3,4],[5,6]])
a = np.array([2,3,4])
print(id(a))
print(A)
print(a)
print(A * a[:,None])

140603431082416
[[1 2]
 [3 4]
 [5 6]]
[2 3 4]
[[ 2  4]
 [ 9 12]
 [20 24]]


In [5]:
a[a > 2] += 100
print(id(a))
print(a)

140603431082416
[  2 103 104]


In [3]:
print(np.repeat(a[None,:], 5, axis=0))

[[2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]]


In [2]:
x = np.array([1,1,1], 'd')

In [5]:
np.vstack(tuple(x for i in range(10)))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
X = np.fromiter((x for i in range(10)), np.dtype((np.double, 3)), 10)
X.dtype, X.shape

(dtype('float64'), (10, 3))

In [ ]:
np.fromiter(

In [13]:
np.hstack((np.array([1],'d'),np.array([0,1,2,3,4],'d')))

array([1., 0., 1., 2., 3., 4.])

In [15]:
np.hstack((np.ones((10,1),'d'),np.full((10,5),-1,'d')))

array([[ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.],
       [ 1., -1., -1., -1., -1., -1.]])

In [3]:
np.multiply(np.array([1,2,3,4,5,6], 'd').reshape((6,1)), np.ones((6,3), 'd'))

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [2]:
G = np.ones((6,3), 'd')
S = np.array([1,2,3,4,5,6], 'd')
G *= S.reshape((-1,1))
print(G)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]
 [6. 6. 6.]]


In [3]:
np.arange(6).reshape(-1,1) @ np.arange(3).reshape(1,-1)

array([[ 0,  0,  0],
       [ 0,  1,  2],
       [ 0,  2,  4],
       [ 0,  3,  6],
       [ 0,  4,  8],
       [ 0,  5, 10]])

In [4]:
S1 = S[1:]

In [8]:
S1[-1]=100
print(S)

[  1.   2.   3.   4.   5. 100.]


In [12]:
S2 = S.take(range(1,len(S)))

In [13]:
S2[-1]=200
print(S)

[  1.   2.   3.   4.   5. 100.]


In [ ]:
S.

In [1]:
%load_ext cython

In [2]:
import numpy as np

In [19]:
%%cython
import numpy as np
cimport numpy as np
b = np.array([True, False])


cdef np.npy_bool[::1] bb = b
cdef int i

print()
for i in range(2):
    # print(type(b[i]))
    print(bb[i])


Content of stderr:
In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/intellimath/.cache/ipython/cython/_cython_magic_b37bd5c9ffbf04a8e2d297f8ac435c8fff9294e1.c:1265:
/usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
1
0
